<a href="https://colab.research.google.com/github/AMALJITH7/numpy/blob/main/numpy_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

How can I slice a 1-dimensional array in NumPy?

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[1:4])

[2 3 4]


2.Can I slice a 2-dimensional array in NumPy?

In [ ]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8],[7,8,5,3],[2,3,4,5]])
print(b[1:3,:3])

[[5 6 7]
 [7 8 5]]


How can I slice an array with a step in NumPy?

In [ ]:
import numpy as np
u=np.array([3,4,5,5,6,7])
print(u[2:4])

[5 5]


4.Can I use negative indices for slicing in NumPy?

In [ ]:
print(a[-4:-2])

[4 5]


What happens if I omit the start or end index in a slice?

In [ ]:
print(a[:4])
print(a[3:])

[1 2 3 4]
[4 5 6 7]


6.Can I modify the original array using slicing in NumPy?

In [ ]:
print(a)
a[0]=0
print(a)

[1 2 3 4 5 6 7]
[0 2 3 4 5 6 7]


7.How can I slice a multi-dimensional array along a specific axis in NumPy?

In [ ]:
import numpy as np
c=np.array([[[1,23,4,5],[4,6,7,8]],[[2,3,45,2],[45,6,6,5]],[[2,3,34,4],[5,3,6,6]]])
print(c[:2,:2,1:3])

[[[23  4]
  [ 6  7]]

 [[ 3 45]
  [ 6  6]]]


8.Can I use boolean indexing for slicing in NumPy

In [ ]:
import numpy as np
e=np.array([2,4,5,6])
f=np.array([True,False,True,False])
print(e[f])


[2 5]


9.How can I reverse the elements of an array using slicing in NumPy?

In [ ]:
print(a[::-1])

[7 6 5 4 3 2 0]


10. Can I use slicing to extract a sub-array from a higher-dimensional array in NumPy?

In [ ]:
import numpy as np
s=np.array([[[1,23,4,5],[4,6,7,8]],[[2,3,45,2],[45,6,6,5]],[[2,3,34,4],[5,3,6,6]]])
print(s[:2,:1])

[[[ 1 23  4  5]]

 [[ 2  3 45  2]]]


11. How can I create a copy of a sliced array in NumPy?

In [ ]:
import numpy as np
x=np.array([3,4,5,6])
y=x[:3]
z=y.copy()
print(z)



[3 4 5]


12. Can I use slicing to assign values to a subset of an array in NumPy?

In [ ]:
print(e)
print(e[2:3])

[2 4 5 6]
[5]


13. Is it possible to slice an array with non-contiguous indices in NumPy?

In [ ]:
print(x[::2])

[3 5]


14. Can I use slicing to extract elements based on a condition in NumPy

In [ ]:
ab=np.array([3,4,5,6,77])
cd=np.array([11,20,4,50,6])
ab[cd>10]



array([3, 4, 6])

15. How can I slice an array along multiple axes in NumPy? (To slice an array along multiple axes, you can use slicing syntax for each axis separated by commas)

In [ ]:
import numpy as np
k=np.array([[[1,23,4,5],[4,6,7,8]],[[2,3,45,2],[45,6,6,5]],[[2,3,34,4],[5,3,6,6]]])
print(k[1:,:,1:3])

[[[ 3 45]
  [ 6  6]]

 [[ 3 34]
  [ 3  6]]]
